### ISSUE TITLE
Crash when loading too many chunks

### ISSUE THREAD

**Issue by Lenni0451** [MCRcortex/nvidium#29]
When I fly through a world for long enough the game crashes with an ArrayIndexOutOfBoundsException:
```
java.lang.ArrayIndexOutOfBoundsException: Index 232 out of bounds for length 232
	at me.cortex.nvidium.managers.RegionManager.createSectionIndex(RegionManager.java:122)
	at me.cortex.nvidium.managers.SectionManager.lambda$uploadSetSection$0(SectionManager.java:73)
	at it.unimi.dsi.fastutil.longs.Long2IntOpenHashMap.computeIfAbsent(Long2IntOpenHashMap.java:489)
	at me.cortex.nvidium.managers.SectionManager.uploadSetSection(SectionManager.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.redirect$beo000$nvidium$redirectUpload(RenderRegionManager.java:523)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:63)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.performPendingUploads(RenderSectionManager.java:383)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:330)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:191)
	at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer.java:7999)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1176)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1263)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:1033)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1221)
	at net.minecraft.client.MinecraftClient.redirect$bgl000$deepclient$universalCrashFix(MinecraftClient.java:8546)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:809)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by Lenni0451** [comment]
Seems to be fixed with the latest Version as it did not occur since I updated.

**Comment by Lenni0451** [comment]
Issue started happening again with version `0.1.16-alpha`.
Same exception but slightly different stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 104 out of bounds for length 104
	at me.cortex.nvidium.managers.RegionManager.createSectionIndex(RegionManager.java:123)
	at me.cortex.nvidium.managers.SectionManager.lambda$uploadSetSection$0(SectionManager.java:73)
	at it.unimi.dsi.fastutil.longs.Long2IntOpenHashMap.computeIfAbsent(Long2IntOpenHashMap.java:489)
	at me.cortex.nvidium.managers.SectionManager.uploadSetSection(SectionManager.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.redirect$cci000$nvidium$redirectUpload(RenderRegionManager.java:533)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.uploadMeshes(RenderRegionManager.java:53)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processChunkBuildResults(RenderSectionManager.java:297)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:285)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191)
	at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer.java:10077)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1184)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1283)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:1052)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1210)
	at net.minecraft.client.MinecraftClient.redirect$zzi000$deepclient$universalCrashFix(MinecraftClient.java:3538)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:799)
	at net.minecraft.client.main.Main.main(Main.java:227)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by MCRcortex** [comment]
Try increasing your vanilla render distance

**Comment by MCRcortex** [comment]
will add a better patch in next release

**Comment by Lenni0451** [comment]
> Try increasing your vanilla render distance

This did not seem to help with the issue.
I now have my render distance on 64 and the `Region Keep Distance` on 64 as well.
