### ISSUE TITLE
1.20 not working

### ISSUE THREAD

**Issue by Andboniels** [MCRcortex/nvidium#40]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Nvidium' (nvidium) 0.1.11-alpha with any version that is compatible with:
		 - iris 1.6.4
Unmet dependency listing:
	 - Mod 'Nvidium' (nvidium) 0.1.11-alpha is incompatible with any version of mod 'Iris' (iris), but a matching version is present: 1.6.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

The mod iris-mc1.20-1.6.4.jar is in the folder!

**Comment by kidofcubes** [comment]
Nvidium is not compatible with Iris.

**Comment by Andboniels** [comment]
Under Dependencies the Iris part is a joke then? 
https://modrinth.com/mod/nvidium/version/0.1.11-alpha

**Comment by Un1q32** [comment]
> Under Dependencies the Iris part is a joke then?
> https://modrinth.com/mod/nvidium/version/0.1.11-alpha

it says incompatible
<img width="606" alt="Screen Shot 2023-06-11 at 3 45 23 AM" src="https://github.com/MCRcortex/nvidium/assets/57970114/206f05eb-f310-4a11-a09e-afe666e296b3">

**Comment by Andboniels** [comment]
Makes no sense to list it under Dependencies when it dont work with it

**Comment by MCRcortex** [comment]
This is an issue with the layout of modrinth unfortunately, hopefully this can be asked to fix
