### ISSUE TITLE
Unexpected error: IllegalStateException: GLERROR: 1281

### ISSUE THREAD

**Issue by BogTheMudWing** [MCRcortex/nvidium#58]
This issue happens rarely, and only when loading lots of chunks.

The report is too long to fit here. Pastebin (expires after six months): https://pastebin.com/rcCAXXsw

**Comment by MCRcortex** [comment]
Can you send the log please (just the last few hundred lines please before the crash)

**Comment by BogTheMudWing** [comment]
```
[16:23:06] [Thread-14/INFO]: Finished in: 133 ms [1348 ms with interruption]
[16:23:07] [CraftPresence/INFO]: Attempting to connect to Discord (5/10)...
[16:23:08] [NBTEditor/Async/UpdateChecker/INFO]: NBT Editor is fully updated!
[16:23:11] [CraftPresence/INFO]: Attempting to connect to Discord (6/10)...
[16:23:17] [CraftPresence/INFO]: Attempting to connect to Discord (7/10)...
[16:23:24] [CraftPresence/INFO]: Attempting to connect to Discord (8/10)...
[16:23:34] [Render thread/INFO]: Adding auth button to the multiplayer screen
[16:23:34] [ForkJoinPool.commonPool-worker-1/INFO]: Verifying Minecraft session...
[16:23:35] [ForkJoinPool.commonPool-worker-1/INFO]: The Minecraft session is valid
[16:23:36] [Render thread/INFO]: Connecting to minecraft.netmillers.com, 25565
[16:23:38] [Render thread/INFO]: Adding auth button to the multiplayer screen
[16:23:39] [CraftPresence/INFO]: Attempting to connect to Discord (9/10)...
[16:23:40] [Render thread/INFO]: Connecting to minecraft.netmillers.com, 25565
[16:23:41] [Netty Epoll Client IO #1/INFO]: Multiplayer Recording is disabled
[16:23:41] [Render thread/INFO]: Enforcing safe world random access
[16:23:41] [Render thread/INFO]: Reloading pipeline on dimension change: OVERWORLD => END
[16:23:41] [Render thread/INFO]: Destroying pipeline OVERWORLD
[16:23:41] [Render thread/INFO]: Creating pipeline for dimension END
[16:23:41] [Render thread/INFO]: Started 10 worker threads
[16:23:44] [Render thread/WARN]: Ambiguity between arguments [itemfactory, display, lore, add, line] and [itemfactory, display, lore, add, text] with inputs: [0, -123, 123]
[16:23:44] [Render thread/WARN]: Ambiguity between arguments [itemfactory, display, lore, set, line] and [itemfactory, display, lore, set, text] with inputs: [0, -123, 123]
[16:23:44] [Render thread/INFO]: Using 3 total BufferBuilder caches
[16:23:44] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[16:23:44] [Render thread/INFO]: Loading all registered leaf blocks.
[16:23:44] [Render thread/INFO]: [System] [CHAT] [Staff] BogTheMudWing joined the game
[16:23:44] [Render thread/INFO]: Loaded 1120 advancements
[16:23:44] [Render thread/INFO]: [System] [CHAT] Welcome, ~Bog!
[16:23:44] [Render thread/INFO]: [System] [CHAT] Type /help for a list of commands.
[16:23:44] [Render thread/INFO]: [System] [CHAT] Type /list to see who else is online.
[16:23:44] [Render thread/INFO]: [System] [CHAT] Players online: 6 - World time: 3:55 PM
[16:23:44] [Render thread/INFO]: [System] [CHAT] You have no new mail.
[16:23:44] [Render thread/INFO]: [System] [CHAT] You're 92 EssentialsX dev build(s) out of date!
[16:23:44] [Render thread/INFO]: [System] [CHAT] Download it here: https://essentialsx.net/downloads.html
[16:23:44] [Render thread/INFO]: Successfully pre-loaded the world!
[16:23:47] [Render thread/INFO]: [System] [CHAT] Warping to ICEWNGPLC.
[16:23:47] [Render thread/INFO]: Reloading pipeline on dimension change: END => OVERWORLD
[16:23:47] [Render thread/INFO]: Destroying pipeline END
[16:23:47] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[16:23:47] [Render thread/INFO]: Stopping worker threads
[16:23:48] [Render thread/INFO]: Started 10 worker threads
[16:23:50] [Render thread/INFO]: Stopping worker threads
[16:23:51] [Render thread/INFO]: Started 10 worker threads
[16:23:53] [Render thread/INFO]: Stopping worker threads
[16:23:53] [Render thread/INFO]: Started 10 worker threads
[16:24:01] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> Bog could you help me with something?
[16:24:06] [Render thread/INFO]: [System] [CHAT] <~Bog> yeah!
[16:24:11] [Render thread/INFO]: [System] [CHAT] <~Bog> what's up?
[16:24:21] [CraftPresence/INFO]: Attempting to connect to Discord (10/10)...
[16:24:22] [Render thread/INFO]: [System] [CHAT] <~dandora> the sky
[16:24:25] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> I accidentaly clicked on a sign that made my sword dissapear
[16:24:37] [Render thread/INFO]: [System] [CHAT] <~Bog> uh oh
[16:24:42] [Render thread/INFO]: [System] [CHAT] <~Bog> can you show me where it is?
[16:24:45] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> ok
[16:25:21] [CraftPresence/ERROR]: Unable to connect to Discord...
[16:25:30] [Render thread/INFO]: [System] [CHAT] iHeron_ left the game
[16:25:41] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> Where are you?
[16:25:46] [Render thread/INFO]: [System] [CHAT] Request sent to ~Pamcaked.
[16:25:46] [Render thread/INFO]: [System] [CHAT] To cancel this request, type /tpacancel.
[16:25:50] [Render thread/INFO]: [System] [CHAT] ~Pamcaked accepted your teleport request.
[16:25:50] [Render thread/INFO]: [System] [CHAT] Teleporting to ~Pamcaked.
[16:26:06] [Render thread/INFO]: [System] [CHAT] <~Bog> oh I know where it is
[16:26:09] [Render thread/INFO]: [System] [CHAT] Teleporting to oldhome.
[16:26:10] [Render thread/INFO]: [System] [CHAT] Set game mode spectator for ~Bog.
[16:26:12] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> Ok thank you
[16:26:13] [Render thread/INFO]: [System] [CHAT] Set game mode creative for ~Bog.
[16:26:19] [Render thread/INFO]: [System] [CHAT] Returning to previous location.
[16:26:20] [Render thread/INFO]: [System] [CHAT] [Staff] PhoenixTalon3 joined the game
[16:26:25] [Render thread/INFO]: [System] [CHAT] <~Queen_Obelisk> wbae
[16:26:25] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> Thank you!
[16:26:28] [Render thread/INFO]: [System] [CHAT] <~Bog> np!
[16:26:30] [Render thread/INFO]: [System] [CHAT] Warping to ICEWNGPLC.
[16:26:35] [Render thread/INFO]: [System] [CHAT] Error: Player not found.
[16:26:38] [Render thread/INFO]: [System] [CHAT] Set flying speed to 10 for ~Bog.
[16:26:59] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> Ok i show you were the thing is
[16:27:04] [Render thread/INFO]: [System] [CHAT] <~Pamcaked> Follow me
[16:27:12] [Render thread/INFO]: [System] [CHAT] Expected '}'
[16:27:12] [Render thread/INFO]: [System] [CHAT] ...t":"Talon's Topography","italic":false,"color":"gold"}]',Lore:['[{"text":"I uh uh uh bowl?","italic":false,"color":"yellow"}]']},Enchantments:[{id:silk_touch,lvl:1}],HideFlags:1} 1<--[HERE]
[16:27:21] [Render thread/INFO]: [System] [CHAT] Gave 1 [Talon's Topography] to [Staff] PhoenixTalon3
[16:28:01] [Render thread/INFO]: [System] [CHAT] Pamcaked left the game
[16:28:44] [Render thread/INFO]: [System] [CHAT] Warping to tnwparty.
[16:29:52] [Render thread/INFO]: [System] [CHAT] PhoenixTalon3 left the game
[16:33:05] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> I'm at the Vault will it let me take anything
[16:33:45] [Render thread/INFO]: [System] [CHAT] <~Bog> You can only take the item at the bottom of the narrow staircase
[16:34:22] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> ok thank you
[16:35:31] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> do I just like push the sign to get it
[16:38:32] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> do I just like push the sign to get it
[16:39:19] [CullThread/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 157 out of bounds for length 129
[16:39:19] [CullThread/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$MapIterator.nextEntry(Int2ObjectLinkedOpenHashMap.java:1171)
[16:39:19] [CullThread/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.next(Int2ObjectLinkedOpenHashMap.java:1679)
[16:39:19] [CullThread/INFO]: [STDERR]: 	at com.google.common.collect.Iterators$1.next(Iterators.java:146)
[16:39:19] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullEntities(CullTask.java:89)
[16:39:19] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:70)
[16:39:19] [CullThread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:39:42] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> it says I can't use TPA except
[16:40:05] [Render thread/INFO]: [System] [CHAT] Set flying speed to 1 for ~Bog.
[16:40:20] [Render thread/INFO]: [System] [CHAT] ~dandora has requested to teleport to you.
[16:40:20] [Render thread/INFO]: [System] [CHAT] To teleport, type /tpaccept.
[16:40:20] [Render thread/INFO]: [System] [CHAT] To deny this request, type /tpdeny.
[16:40:20] [Render thread/INFO]: [System] [CHAT] This request will timeout after 30 seconds.
[16:40:22] [Render thread/INFO]: [System] [CHAT] Teleport request accepted.
[16:40:22] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.cod.ambient
[16:40:26] [Render thread/INFO]: [System] [CHAT] ~Queen_Obelisk has requested to teleport to you.
[16:40:26] [Render thread/INFO]: [System] [CHAT] To teleport, type /tpaccept.
[16:40:26] [Render thread/INFO]: [System] [CHAT] To deny this request, type /tpdeny.
[16:40:26] [Render thread/INFO]: [System] [CHAT] This request will timeout after 30 seconds.
[16:40:28] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> it says I can't use TPA except
[16:40:28] [Render thread/INFO]: [System] [CHAT] Teleport request accepted.
[16:40:53] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.tropical_fish.ambient
[16:41:03] [Render thread/INFO]: [System] [CHAT] Set game mode spectator for ~Bog.
[16:41:13] [Render thread/INFO]: [System] [CHAT] <~Bog> click the button to take it
[16:41:25] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> yay
[16:41:29] [Render thread/INFO]: [System] [CHAT] Set game mode creative for ~Bog.
[16:41:51] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> it worked
[16:42:04] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> thank you
[16:42:11] [Render thread/INFO]: [System] [CHAT] <~Bog> np!
[16:42:28] [Render thread/INFO]: [System] [CHAT] Set flying speed to 10 for ~Bog.
[16:42:30] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> what does that mean
[16:42:35] [Render thread/INFO]: [System] [CHAT] [SeW] Calwaii joined the game
[16:42:37] [Render thread/INFO]: [System] [CHAT] <~Bog> no problem
[16:42:38] [Render thread/INFO]: [System] [CHAT] <~Queen_Obelisk> weba
[16:42:41] [Render thread/INFO]: [System] [CHAT] <~dandora> wb
[16:42:45] [Render thread/INFO]: [System] [CHAT] <Wolfgirl136> ok
[16:42:48] [Render thread/INFO]: [System] [CHAT] <~Marine> hello
[16:42:52] [Render thread/INFO]: [System] [CHAT] <~Queen_Obelisk> hiii
[16:43:03] [Render thread/INFO]: [System] [CHAT] <~Marine> hello silver
[16:43:10] [Render thread/INFO]: [System] [CHAT] <~Queen_Obelisk> hiii calwaii
[16:43:19] [Render thread/INFO]: [System] [CHAT] <~Marine> hi silver
[16:43:58] [Render thread/INFO]: OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[16:43:58] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: GLERROR: 1281
```

**Comment by MCRcortex** [comment]
If this is still an issue in nvidium 0.2.5 please reopen the issue
